apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "triton.fullname" . }}
  labels:
    {{- include "triton.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "triton.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "triton.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: models
        nfs:
          server: {{ .Values.volumes.nfs.server | quote }}
          path: {{ .Values.volumes.nfs.path | quote }}
          readOnly: {{ .Values.volumes.nfs.readOnly }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "triton.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- range .Values.image.command }}
          command:
            - {{ . | quote }}
          {{- end }}
          {{- range .Values.image.args }}
          args:
            - {{ . | quote}}
          {{- end }}
          volumeMounts:
            - mountPath: /models
              name: models
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v2
              port: http
          readinessProbe:
            httpGet:
              path: /v2
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
